apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_HOST: main-db-svc
  POSTGRES_DB: db_task
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres