apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    db: postgres
spec:
  selector:
    matchLabels:
      app: main-db-svc # has to match .spec.template.metadata.labels
  serviceName: "main-db-svc"
  replicas: 2
  template:
    metadata:
      labels:
        app: main-db-svc # has to match .spec.selector.matchLabels
    spec:
      volumes:
      - name: task-pv-storage
        persistentVolumeClaim:
          claimName: task-pv-claim
      terminationGracePeriodSeconds: 10
      containers:
      - name: postgres
        image: postgres:latest
        envFrom:
          - configMapRef:
              name: postgres-config
        volumeMounts:
        - mountPath: database
          name: task-pv-storage
        ports:
        - containerPort: 5432
          name: postgres-port