apiVersion: apps/v1
kind: Deployment
metadata:
  name: gorgias-front-deployment
  labels:
    app: front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: frontapp
        image: ibrahimtounkaradevgorgias/gorgias_front:1.0
        command:
        - /bin/bash
        - -c
        - service apache2 stop;
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: docker-hub-cred
