apiVersion: apps/v1
kind: Deployment
metadata:
  name: gorgias-front-deployment
  labels:
    app: front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: frontapp
        image: ibrahimtounkaradevgorgias/gorgias_front:1.0
        envFrom:
          - configMapRef:
              name: postgres-config
        stdin: true
        tty: true
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - "-c"
            - service apache2 start
          initialDelaySeconds: 10
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: docker-hub-cred
