apiVersion: v1
kind: Service
metadata:
  name: replica-db-svc
  labels:
    app: replica-db-svc
spec:
  ports:
  - port: 5432
    targetPort: 5433
  selector:
    app: main-db-svc

---
apiVersion: v1
kind: Service
metadata:
  name: front-svc
  labels:
    app: front-svc
spec:
  type: NodePort
  selector:
    app: front
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007
    
---
apiVersion: v1
kind: Service
metadata:
  name: main-db-svc
  labels:
    app: main-db-svc
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: main-db-svc    